version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolwear_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./outputs:/app/outputs:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: toolwear_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend